objects/Bling_Bling__c.object
<CustomObject>
    <description>Demo object used for demo purposes.
Update this every time I have a new demo.</description>
    <fields>
        <fullName>External_URL__c</fullName>
        <label>External URL</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>https://{!Environment.EXT_URL}</fullName>
                </value>
                <value>
                    <fullName>https://static.externalurl.com</fullName>
                </value>
                <value>
                    <fullName>https://www.externalurl.com</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>TextArea</type>
    </fields>
    <label>Bling Bling</label>
    <nameField>
        <label>Bling Bling Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bling Blings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BlingBlingController.cls
public with sharing class BlingBlingController {
    @AuraEnabled
    public static Bling_Bling__c setDefaultInfo(Bling_Bling__c a) {
        
        if (a==null) { 
            a = new Bling_Bling__c(Name='Default');
        }
        a.Name = 'Major Bling Bling';
        a.Price__c = 999.99;
        a.External_URL__c = 'https://{!Environment.EXT_URL}';
        a.Reason__c = 'I love bling blings!';
        
        return a;

    }

}