objects/Bling_Bling__c.object
<CustomObject>
    <description>Demo object used for demo purposes.
Update this every time I have a new demo.</description>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>TextArea</type>
    </fields>
    <label>Bling Bling</label>
    <nameField>
        <label>Bling Bling Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bling Blings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BlingBlingControllerTest.cls
@isTest
public class BlingBlingControllerTest {

    @isTest
    public static void testSetDefaultInfo() {
        Bling_Bling__c testObj;
        testObj = BlingBlingController.setDefaultInfo(testObj);
        if (testObj != null) {
            System.assertEquals(testObj.Reason__c,'I love bling blings!');
        }
        
        testObj = new Bling_Bling__c(Name='Default');
        testObj = BlingBlingController.setDefaultInfo(testObj);
        System.assertEquals(testObj.Name,'Major Bling Bling');
    }


}